name: neuralmusic

channels:
  - pytorch
  - fastai
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pytorch=1.3
  - torchvision=0.4
  - black
  - pytest
  - pytest-sugar
  - flake8
  - python-dotenv
  - pip>=19.3.1
  - pip:
      - music21
      - fastparquet
      - "git+https://github.com/fastai/fastai2"
