name: neuralmusic

channels:
  - pytorch
  - fastai
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pytorch=1.3
  - black
  - dask
  - python-snappy
  - pip>=19.3.1
  - pip:
      - music21
      - fastparquet
      - prefect[viz]
      - hydra-core
      - hydra_colorlog
      - "git+https://github.com/fastai/fastai2"
