project: neuralmusic

training:
  epochs: 10
  batch_size: 128
  seq_len: 60
  validation_split: 0.2

data:
  etl:
    dry_run: False
    partition_size: 50
    threads_per_worker: 4

defaults:
  - model: dual
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
