project: neuralmusic

data:
  etl:
    dry_run: False
    partition_size: 50
    num_workers: 2
    threads_per_worker: 1

defaults:
  - model: dual
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
