project: neuralmusic

data:
  etl:
    dry_run: False
    partition_size: 50
    num_workers: 1
    threads_per_worker: 4

defaults:
  - model: dual
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
