#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Triplet": "01_midi.ipynb",
         "parse_single_note": "01_midi.ipynb",
         "parse_chord": "01_midi.ipynb",
         "parse_rest": "01_midi.ipynb",
         "parse_midi_file": "01_midi.ipynb"}

modules = ["midi.py"]

git_url = "https://github.com/codegram/neuralmusic/tree/master/"

def custom_doc_links(name): return None